// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKLj6T3KV8c82jFUyilQ-iIrnbSIErahg',
    appId: '1:951403946633:web:e321fdaa7b3a0915f25c58',
    messagingSenderId: '951403946633',
    projectId: 'tester-semeton',
    authDomain: 'tester-semeton.firebaseapp.com',
    databaseURL: 'https://tester-semeton-default-rtdb.firebaseio.com',
    storageBucket: 'tester-semeton.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrQDuDd6VthVFs7j7T7wAkLTjiEuok-BY',
    appId: '1:951403946633:android:f247200b702a7abaf25c58',
    messagingSenderId: '951403946633',
    projectId: 'tester-semeton',
    databaseURL: 'https://tester-semeton-default-rtdb.firebaseio.com',
    storageBucket: 'tester-semeton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6iMhtGN6grX-JpFT_qCm3Lo9W4lKnMtY',
    appId: '1:951403946633:ios:440f3e1de8aae925f25c58',
    messagingSenderId: '951403946633',
    projectId: 'tester-semeton',
    databaseURL: 'https://tester-semeton-default-rtdb.firebaseio.com',
    storageBucket: 'tester-semeton.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6iMhtGN6grX-JpFT_qCm3Lo9W4lKnMtY',
    appId: '1:951403946633:ios:440f3e1de8aae925f25c58',
    messagingSenderId: '951403946633',
    projectId: 'tester-semeton',
    databaseURL: 'https://tester-semeton-default-rtdb.firebaseio.com',
    storageBucket: 'tester-semeton.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKLj6T3KV8c82jFUyilQ-iIrnbSIErahg',
    appId: '1:951403946633:web:32d0c2547d5a2e10f25c58',
    messagingSenderId: '951403946633',
    projectId: 'tester-semeton',
    authDomain: 'tester-semeton.firebaseapp.com',
    databaseURL: 'https://tester-semeton-default-rtdb.firebaseio.com',
    storageBucket: 'tester-semeton.appspot.com',
  );

}